Fix `v-model` Vue Compiler Warnings
VueCompilerError: v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>