[release-2.9] build-extension-catalog fails
Resolves #12993.

Empty tagged_release causes trailing error.

Run yarn parse-tag-name  12645625456 "catalog"
yarn run v1.22.22
warning package.json: No license field
$ ./node_modules/@rancher/shell/scripts/extension/parse-tag-name 12645625456 catalog
Parse tag name - evaluating release tag 12645625456
release tag doesn't match any chart tag: 12645625456. Check your pkg/<!-YOUR-EXT-> folders and corresponding versions to complete the match
invalid run-id "catalog"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
Error: Process completed with exit code 1.

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>